In [4]:
import pandas as pd
import numpy as np
import requests
from nba_api.stats import endpoints

In [5]:
data = endpoints.leagueleaders.LeagueLeaders()# Here we access the leagueleaders module through endpoints & assign the class to "data"


# Our "data" variable now has built in functions such as creating a dataframe for our data
df = data.league_leaders.get_data_frame()
df.head()

,PLAYER_ID,RANK,PLAYER,TEAM,GP,MIN,FGM,FGA,FG_PCT,FG3M,...,REB,AST,STL,BLK,TOV,PF,PTS,EFF,AST_TOV,STL_TOV
0,201935,1,James Harden,HOU,61,2241,603,1386,0.435,271,...,388,450,106,53,273,206,2096,1937,1.65,0.39
1,1629027,2,Trae Young,ATL,60,2120,546,1249,0.437,205,...,255,560,65,8,289,104,1778,1596,1.94,0.23
2,203078,3,Bradley Beal,WAS,57,2053,593,1303,0.455,170,...,242,347,71,23,194,126,1741,1448,1.79,0.37
3,203507,4,Giannis Antetokounmpo,MIL,57,1763,623,1139,0.547,83,...,783,329,59,58,209,173,1690,1985,1.57,0.28
4,203081,5,Damian Lillard,POR,58,2140,531,1162,0.457,226,...,250,453,59,21,168,98,1677,1612,2.70,0.35